name: egp_rate_tracker
description: "EGP Rate Tracker — live & historical Egyptian Pound exchange rates."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.12.0
  intl: ^0.20.2

  # State management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0

  # Dependency injection
  get_it: ^8.0.3

  # Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Connectivity
  flutter_offline: ^4.0.0

  # Localization
  easy_localization: ^3.0.7+1

  # Charts
  fl_chart: ^0.70.2

  # Loading UI
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  retrofit_generator: ^10.2.8
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  freezed: ^3.0.6

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
